/* TABLAS DE LA APLICACIÓN CITES-TIME.
 */
/* Simple */
CREATE DATABASE IF NOT EXISTS citestime
  CHARACTER SET utf8
  COLLATE utf8_unicode_ci;
GRANT SELECT,INSERT,UPDATE,DELETE ON citestime.* TO 'citestime'@'%' IDENTIFIED BY 'citestime';
GRANT SELECT,INSERT,UPDATE,DELETE ON citestime.* TO 'citestime'@'localhost' IDENTIFIED BY 'citestime';
FLUSH PRIVILEGES;
USE citestime;

/* Multimedia */
CREATE TABLE IF NOT EXISTS ARCHIVO (
  ARCH_ID BIGINT NOT NULL AUTO_INCREMENT,
  ARCH_BYTES LONGBLOB NOT NULL,
  VERSION INT, /* Requerido para transacciones de JPA. */
  CONSTRAINT ARC_PK PRIMARY KEY (ARCH_ID)
) ENGINE InnoDb;

/* Muchos a Muchos, Seguridad */
CREATE TABLE IF NOT EXISTS USUARIO (
  USU_ID VARCHAR(16) NOT NULL,
  USU_CONTRA VARCHAR(100) NOT NULL,
  USU_NOMBRE VARCHAR(255) NOT NULL,
  USU_DIRECCION VARCHAR(255) NOT NULL,
  USU_SEXO VARCHAR(255) NOT NULL,
  USU_FECHA_NAC DATETIME NOT NULL,
  USU_TELEFONO DECIMAL(10),
  USU_DESCRIPCION VARCHAR(255),
  IMAGEN_ID BIGINT ,
  VERSION INT, /* Requerido para transacciones de JPA. */
  UPPER_ID VARCHAR(255), /* Requerido para ORDER BY de JPA. */
  CONSTRAINT USU_PK PRIMARY KEY (USU_ID),
  CONSTRAINT USU_IDCH CHECK (LENGTH(USU_ID) >= 8),
  CONSTRAINT USU_COCH CHECK (USU_CONTRA <> ''),
  CONSTRAINT USU_NOCH CHECK (USU_NOMBRE <> ''),
  CONSTRAINT USU_IMUN UNIQUE (IMAGEN_ID),
  CONSTRAINT USU_IMG FOREIGN KEY (IMAGEN_ID) REFERENCES ARCHIVO(ARCH_ID)
) ENGINE InnoDb;
CREATE TABLE IF NOT EXISTS ROL (
  ROL_ID VARCHAR(255) NOT NULL,
  ROL_DESCRIPCION VARCHAR(255) NOT NULL,
  VERSION INT, /* Requerido para transacciones de JPA. */
  UPPER_ID VARCHAR(255), /* Requerido para ORDER BY de JPA. */
  CONSTRAINT ROL_PK PRIMARY KEY (ROL_ID)
) ENGINE InnoDb;
CREATE TABLE IF NOT EXISTS USUARIO_ROL (
  USU_ID VARCHAR(16) NOT NULL,
  ROL_ID VARCHAR(255) NOT NULL,
  CONSTRAINT UR_PK PRIMARY KEY (USU_ID, ROL_ID),
  CONSTRAINT UR_USU FOREIGN KEY (USU_ID) REFERENCES USUARIO(USU_ID),
  CONSTRAINT UR_ROL FOREIGN KEY (ROL_ID) REFERENCES ROL(ROL_ID)
) ENGINE InnoDb;

CREATE TABLE IF NOT EXISTS LUGAR (
  LUG_ID BIGINT NOT NULL AUTO_INCREMENT,
  LUG_NOMBRE VARCHAR(255),
  LUG_DESCRIPCION VARCHAR(255),
  IMAGEN_ID BIGINT ,
  VERSION INT, /* Requerido para transacciones de JPA. */
  UPPER_ID VARCHAR(255), /* Requerido para ORDER BY de JPA. */
  CONSTRAINT LUG_PK PRIMARY KEY (LUG_ID),
  CONSTRAINT LUG_NOCH CHECK (LUG_NOMBRE <> ''),
  CONSTRAINT LUG_IMUN UNIQUE (IMAGEN_ID),
  CONSTRAINT LUG_IMG FOREIGN KEY (IMAGEN_ID) REFERENCES ARCHIVO(ARCH_ID)
) ENGINE InnoDb;

/* Muchos a un Lugar */
CREATE TABLE IF NOT EXISTS CITA (
  CITA_ID BIGINT NOT NULL AUTO_INCREMENT,
  CITA_FECHA DATETIME NOT NULL,
  CITA_HORA DATETIME NOT NULL,
  CITA_CALIFICACION INT,
  USU_ORIGEN VARCHAR(255),
  USU_DESTINO VARCHAR(255),
  LUG_ID BIGINT NOT NULL,
  VERSION INT, /* Requerido para transacciones de JPA. */
  CONSTRAINT CITA_ID PRIMARY KEY (CITA_ID),
  CONSTRAINT CITA_LUG FOREIGN KEY (LUG_ID) REFERENCES LUGAR(LUG_ID)
) ENGINE InnoDb;
/* Sincronización */
CREATE TABLE IF NOT EXISTS AVISO (
  AVI_ID VARCHAR(255) NOT NULL,
  AVI_TITULO VARCHAR(255) NOT NULL,
  AVI_TEXTO VARCHAR(255) NOT NULL,
  AVI_MODIFICACION BIGINT NOT NULL,
  AVI_ELIMINADO INT NOT NULL,
  CONSTRAINT AVI_PK PRIMARY KEY (AVI_ID),
  CONSTRAINT AVI_TICH CHECK (AVI_TITULO <> ''),
  CONSTRAINT AVI_TXCH CHECK (AVI_TEXTO <> '')
) ENGINE InnoDb;
